name = "bank-demo"
main = "src/index.ts"
compatibility_date = "2026-03-10"
workers_dev = false

routes = [
  { pattern = "bank.kuma.homes", custom_domain = true }
]

[vars]
BASE_URL = "https://bank.kuma.homes"
LILIUM_BASE_URL = "https://lilium.kuma.homes"

[durable_objects]
bindings = [{ name = "ACCOUNT_DO", class_name = "AccountDurableObject" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AccountDurableObject"]
